# MIT License
# Copyright (c) 2020 Hongrui Zheng

bridge:
  ros__parameters:
    # topics and namespaces
    ego_namespace: 'ego_racecar'
    ego_scan_topic: 'scan'
    ego_odom_topic: 'odom'
    ego_opp_odom_topic: 'opp_odom'
    ego_drive_topic: 'drive'
    opp_namespace: 'opp_racecar'
    opp_scan_topic: 'opp_scan'
    opp_odom_topic: 'odom'
    opp_ego_odom_topic: 'opp_odom'
    opp_drive_topic: 'opp_drive'

    # transform related
    scan_distance_to_base_link: 0.275
    
    # laserscan parameters
    scan_fov: 4.7
    scan_beams: 1080

    # map parameters
    map_path: "/home/jsun/f1_sim_ws/src/f1tenth_gym_ros/maps/Spielberg_map"
    map_img_ext: '.png'

    # opponent parameters
    num_agent: 2

    # ego starting pose on map (30m 공터의 정중앙)
    sx: 0.0
    sy: 0.0
    stheta: 0.0

    # opp starting pose on map (내 차 기준 왼쪽으로 2m 옆)
    sx1: 0.0
    sy1: 2.0
    stheta1: 0.0

    # teleop
    kb_teleop: False